#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin-vue"
name = "Jellyfin Vue Client"
description.en = "Modern web client for Jellyfin"
description.fr = "Client web moderne pour Jellyfin"

version = "2026.09.22~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/jellyfin/jellyfin-vue"
demo = "https://jf-vue.pages.dev"

fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin-vue"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jellyfin/jellyfin-vue/archive/363446df350b8a323173108d3bb56abc22c2d440.tar.gz"
    sha256 = "88d5efbe59a2ee5424846f8a8f2e5364422444ba7081cb00a1ad1b8e60d46a70"

    autoupdate.upstream = "https://github.com/jellyfin/jellyfin-vue/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.nodejs]
    version = "24"
