#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin-vue"
name = "Jellyfin Vue Client"
description.en = "Modern web client for Jellyfin"
description.fr = "Client web moderne pour Jellyfin"

version = "2026.05.08~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/jellyfin/jellyfin-vue"
demo = "https://jf-vue.pages.dev"

fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin-vue"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jellyfin/jellyfin-vue/archive/a3f41c7dcb3dbcfd9ee883018ff528c3b9a67585.tar.gz"
    sha256 = "9062465194b1fe4c1e87424526e9105e20b7dab1625b7a2c8acb9e21e86d1568"

    autoupdate.upstream = "https://github.com/jellyfin/jellyfin-vue/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.nodejs]
    version = "24"
