#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/source" --full_replace


ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

ynh_script_progression "Building Jellyfin Vue... (this will take some time and resources!)"

_patch_config_json "$install_dir/source"
_npm_build_install "$install_dir/source" "$install_dir/www" "$path/"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

# Check if Jellyfin is installed, and configure it as defaultServerURL.
for url in $(_list_jellyfin_urls); do
    _append_to_server_urls "$install_dir/www/config.json" "$url"
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
